---
# Default variables for dotfiles role

# Method for dotfiles deployment
# true: create symlinks (default, allows live editing)
# false: copy files (standalone, no dependency on source)
dotfiles_use_symlinks: false