- name: "Check if burpsuite-ca.der exists"
  stat:
    path: /usr/local/share/ca-certificates/burpsuite-ca.der
  register: burp_cert
  
- name: "Copying Burp Script"
  copy:
    src: files/getburpcert.sh
    dest: /tmp/getburpcert.sh
    mode: 0744
  when: burp_cert.stat.exists == False

- name: "Executing bash script to Download CA Certificate"
  shell:
    /tmp/getburpcert.sh
  when: burp_cert.stat.exists == False

- name: "Copying CA Certificate to /usr/local/share/ca-certificates"
  copy:
    src: /tmp/cacert.der
    dest: /usr/local/share/ca-certificates/burpsuite-ca.der
    owner: root
    group: root
    mode: 0644
  become: true
  become_method: sudo
  when: burp_cert.stat.exists == False
  
- name: Copy BurpSuite Community Config
  template:
    src: "templates/UserConfigCommunity.json.j2"
    dest: "/home/{{ ansible_user_id }}/.BurpSuite/UserConfigCommunity.json"