---
- name: ensure dependencies for pyenv are installed
  apt:
    name:
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - libncurses5-dev
      - libncursesw5-dev
      - libffi-dev
      - liblzma-dev
      - tk-dev
      - libgdbm-dev
      - libnss3-dev
      - uuid-dev
    state: present
  become: true

- name: install pyenv
  shell: curl -fsSL https://pyenv.run | bash
  args:
    creates: "~/.pyenv"